[project]
name = "snyk-insights"
version = "0.1.0"
description = "Read and analyze Snyk security issues CSV files"
requires-python = ">=3.13"
dependencies = [
    "pydantic>=2.0.0",
    "jinja2>=3.0.0",
]
